#pragma once

// Scene object and PSO layers
#define SKY 0
#define OPAQUELAYER SKY + 1
#define NOTOPAQUELAYER OPAQUELAYER +1
#define SKINNEDOPAQUELAYER OPAQUELAYER +2
#define SKINNEDNOTOPAQUELAYER OPAQUELAYER +3
#define NOTOPAQUELAYERGH OPAQUELAYER +4
#define LAYERSCOUNT NOTOPAQUELAYERGH - SKY + 1

// InputLayout variants
#define ILV1 0
#define ILV2 ILV1 +1 
#define ILVCOUNT ILV2 - ILV1 + 1
